### ISSUE TITLE
[BUG] UI bugs

### ISSUE THREAD

**Issue by nautilusx** [mateusz-bak/openreads-android#221]
**Describe the bug**
@mateusz-bak thanks for your great app. I found some ui bugs in the 2.0.0-rc3.

**To Reproduce**
**1. Welcome screen cuts off the translated text at the end.**

![Screenshot_20230220-163349_Openreads 2_013325](https://user-images.githubusercontent.com/8766955/220395599-c9dd33d5-ddb4-493a-9669-1b4d1b460011.png)

**2. Status of the book is too small. Better 2 lines.**

![Screenshot_20230220-163513_Openreads 2_013323](https://user-images.githubusercontent.com/8766955/220396126-f66b4aaf-21b4-4154-b7f6-f64b3aa76668.png)

**3. Text for the challenge is cut off. Better 2 lines. And the Legend for diagram is not well readable.**

![Screenshot_20230220-174757_Openreads 2_013259](https://user-images.githubusercontent.com/8766955/220396950-66379430-040d-43a6-bce7-8720d84d180f.png)

**Additional info(please complete the following information):**
 - Manufacturer and model: bq X
 - Android version: 13 (LineageOS 20)
 - App version: v2.0.0-rc3
 - App source (F-Droid, Google Play, Github): GitHub

**Comment by mateusz-bak** [comment]
Thanks for reporting @nautilusx. Can you add your phone model and whether you modified font size etc?

**Comment by nautilusx** [comment]
I made an update. There is no modified font size.

**Comment by mateusz-bak** [comment]
@nautilusx 
1 - The introduction screen has scrollbars in case of the text being cut off (anyway I'll be changing how it looks soon)
2 - I decreased the inner padding in the buttons so the text will be a little bigger. I won't be adding two lines because at the beginning when no status is selected the texts are bigger - and after clicking user has an idea whet they are for.
3- Added text wrap for the challenge box and improved displaying of the chart.

Thanks for the points, will be released in 2.0.0 this week if all goes well
