### ISSUE TITLE
[FEATURE_REQUEST] Search Open Library by more than book title

### ISSUE THREAD

**Issue by BradNut** [mateusz-bak/openreads-android#311]
**Is your feature request related to a problem? Please describe.**
It would be helpful to be able to search for all books by a certain author or search for an author with the ability to view all books written by that author. This would be helpful for bulk adding it books into your library when going through a book series.

For example, if I'm on a fifth book of Red Rising by Pierce Brown but and would like to add all five books to my library I would currently need to remember the title of each book, search for each individually, and add one by one. If I were able to search by author, Pierce Brown, and then view the books he wrote.

This mitigates the issue of remembering every book title for a long running book series, allows for future bulk add UI it desired, allows discovery of new books by that author, keeps the user in the app without the need to leave to source title, and saves time from having to enter each book title in manually (Poentially if the UI allows adding from that view).

**Describe the solution you'd like**

Looking at the code for the app it seems to just be doing a GET query param search to the open library URL. Their API already allows searching by different types like authors and then then drilling down to view all works by that author.

See query for author Pierce Brown: `https://openlibrary.org/search/authors?q=Pierce+Brown&mode=everything`

Author page URL after drilling down into the author page: `https://openlibrary.org/authors/OL7621609A/Pierce_Brown`

Search for book titles by that author: `https://openlibrary.org/authors/OL7621609A/Pierce_Brown?q=Red+Rising`

**Describe alternatives you've considered**
Alternatives are just remembering the book names by an author or using an alternative source to find all books by that author and then manually entering each one in. While not a huge deal it takes you out of the context of the app and reduces the want to use the app for cataloging.

**Comment by mateusz-bak** [comment]
Hi, so you think adding a "filter" to the Open Library search would be useful? And by filter I mean changing the API enpoint for search query.

**Comment by apobrt** [comment]
I make a proposal: why don't we implement a filter option list in the current search screen?
As already said, the Open Library API has a simple implementation of filter options, so we "only" need to expose these options graphically.
I thought of a tag/chip list below the search bar, like the "finish year" or tags in the sort/filter panel, but exclusives.
I made an ugly mockup to show what I have in mind:

![filter_search](https://github.com/mateusz-bak/openreads-android/assets/45424365/44a58196-b07a-45ea-beea-0e38ae07668d)

The con is that they can't be combined, because in these cases we would need more input bar.
The pro is that I think is simple enough, and so very intuitive, and yet very powerful.

The corresponding API of the mockup would be something like
`https://openlibrary.org/search?author=abcde`

**Comment by mateusz-bak** [comment]
<img width="300" alt="obraz" src="https://github.com/mateusz-bak/openreads-android/assets/32651935/00511efb-e946-4652-94ec-633d5ef491f3">

Alright, I added the four options to search books as per the screenshot
