### ISSUE TITLE
UI Improvement idea

### ISSUE THREAD

**Issue by armand-leguillou** [mateusz-bak/openreads-android#317]
Hello everyone,
I spot a couple of things that i think they could be improved. I would like to help by coding but I'm not developper at all. So I made a Figma design file to explain what I mean : [here](https://www.figma.com/file/zkG1DX7Zu2rwlhTQZBPfTV/Openreads-UI-Improvements-%F0%9F%93%96?type=design&mode=design&t=x5KLCcYHmBQv8jXn-1).

On the left you can see the homescreen of Openreads. I tried to redesign the top of the screen by adding a real search bar and remove the three dots at the top-right. Instead of the three dots, I put two new icons: a gear for the settings and a chart for the statistics!

On the right you can see that i also remove the three dots and replacing it by two icons (edit and delete). I replace the black block that was on the top by the blur effect of the background.

All of the icons come from the Google Materials Icons (open-source).

Best regards,
armand (sorry for the mistakes, I'm not an english-speaker)

**Comment by mateusz-bak** [comment]
Hello @armand-leguillou looks awesome at the first glance! Thanks for your effort.

I'll take a closer look and probably will have some feedback but I need to find some time to do it this week.

**Comment by armand-leguillou** [comment]
thank you for your app!  I am obviously open to your feedback.  however I'm not a ui designer at all, but I'm very interested in (so my work may not be good at all).
good week! (🚀)

**Comment by mateusz-bak** [comment]
Hi @armand-leguillou I implemented the book screen with extended background image. I'm not removing the three dots icons - I think more icons will clutter the UI.

And for the first screen I also don't like the idea of having 5 icons instead of 3 (I would even like to see 2 icons or only the three dots there). And unfortunately the search bar is implemented like that because it was easier to move to separate search screen then to add the search logic to the 1st screen.

Let me know if you have any thoughts and check out attached screenshot.

<img src="https://user-images.githubusercontent.com/32651935/269433907-6fca8d04-f12e-472d-9511-d6a0943ff54d.jpg" width="50%">

**Comment by armand-leguillou** [comment]
wonderful!!! thank you!
I can't wait to see it on my phone!
