### ISSUE TITLE
[FEATURE_REQUEST] Filtering the books by tags

### ISSUE THREAD

**Issue by starryveshch** [mateusz-bak/openreads-android#40]
**Is your feature request related to a problem? Please describe.**
If I have tagged some books as *science fiction* in the "For Later" list, it is hard to find them again.

**Describe the solution you'd like**
A functionality to filter the books by selecting multiple tags. If I want some classic science fiction books, then I can find them by selecting the tags *classic* and *science fiction*.

**Comment by mateusz-bak** [comment]
Hello @starryveshch I found some issues about tags and filtering that will be fixed in the next release:

1. Tags from "for later" are not displayed in the sort dialog - will be displayed there
2. Current tags filtering works like "OR" - will be working like "AND" so you can display just books that have both science fiction and classic tag.
3. If book have for example two tags and we select them both books is displayed two times - will be fixed to display only once

I also plan to display tags of each book in the books list (optional) and add genres to books down the road.

Let me know if that covers your proposals or there is anything else I can help.

**Comment by mateusz-bak** [comment]
> > ```
> > 2. Current tags filtering works like "OR" - will be working like "AND" so you can display just books that have both science fiction and classic tag.
> > ```
> 
> Is it possible to have both "AND" and "OR" filters?
> 
> In Calibre, if I want to find classic science fiction or horror books, then I can filter books like this,
> 
> `tags:"=classics" and tags:"=science fiction" or tags:"=horror" `
> 
> > Let me know if that covers your proposals or there is anything else I can help
> 
> Can you add auto-completion or selection of used tags? It will make adding tags easier.
> 
> By the way, thanks for your work. I really love the app.

Good idea with having both OR and AND, will think how to implement it nicely. And the tags auto-completion is planned! Thanks for the contributions!

**Comment by mateusz-bak** [comment]
@starryveshch sorry I took some time but I added AND & OR tags filtering. Will be implemented with v1.16.0 soon!

**Comment by starryveshch** [comment]
> @starryveshch sorry I took some time but I added AND & OR tags filtering. Will be implemented with v1.16.0 soon!

Thanks a lot for that.
