### ISSUE TITLE
[FEATURE_REQUEST] Books count

### ISSUE THREAD

**Issue by mizzunet** [mateusz-bak/openreads-android#95]
**Is your feature request related to a problem? Please describe.**
isn't it good idea to display the total number of items in section Finished, In Progress and For Later?

**Describe the solution you'd like**
Either here,
![image](https://user-images.githubusercontent.com/10193999/170922115-c5ceb6e6-397b-4b9d-8ee4-c4ac5a8c6192.png)

or perhaps at the top,
![image](https://user-images.githubusercontent.com/10193999/170922153-2e2e28c0-d61a-4701-9986-489cdaed52b7.png)

**Describe alternatives you've considered**
Well, we have Statistics. But displaying just the count here would be handy, I guess

**Comment by apobrt** [comment]
Instead of placing the counter near the tab labels (which I'm not a big fan), why not displaying them in the header of each page? Maybe adding another row in the header (below the one that says "Openreads") with the writing "Finished"/"In progress"/"For later" and the counter, that hides when scrolling the page down

**Comment by mateusz-bak** [comment]
Added a header with number of currently displayed books in the list and all books from the list above the list.
